// Generated by Wrangler by running `wrangler types`

interface Env {
	OAUTH_KV: KVNamespace;
	CF_CLIENT_ID: string;
	CF_CLIENT_SECRET: string;
	MCP_OBJECT: DurableObjectNamespace<import("./src/index").MyMCP>;
}
